### ISSUE TITLE
problem in 3D recon on ETH. Points shifted from reference images

### ISSUE THREAD

**Issue by GabbySuwichaya** [lzx551402/ASLFeat#8]
Hi ! Thank you for the great work and sharing! ASLfeat is a very competitive method and is currently one of the best in MMA. 

So, I have been interested in the ASLfeat's performance on 3D reconstruction as it seems that ASLfeat is doing very well in providing high registered images and sparse points. 

So, I run a small test using the output from your package and integrate it into ETH Benchmark evaluation on Herzjesu.  

-  The problem is that I have got the following results. The sparse points projected on images are shifted from where it supposed to be (as shown in the image number 8 on the right).  

Could you advice if I should set anything in addition ?  

Here is the results of ASLfeat.  
 
![Screenshot from 2020-09-18 02-27-54](https://user-images.githubusercontent.com/49115268/93506821-c329f800-f957-11ea-9068-d7ebbb83cc43.png)

Also, just to give a reference. Here is the results of SIFT. The other methods seem to do ok too. 

![Screenshot from 2020-09-18 02-47-16](https://user-images.githubusercontent.com/49115268/93508207-5b74ac80-f959-11ea-8b49-d2958de3fa65.png)

Also, I attached my setting in the config here. 
If it happened that I did not set something right, please let me know:.

```
data_name: 'eth'
data_split: ['Herzjesu', 'Fountain', 'South-Building']  #['Gendarmenmarkt', 'Madrid_Metropolis', 'Tower_of_London']
data_root: '/mnt/HDD4TB1/local-feature-evaluation/datasets'
dump_root: 
truncate: [0, null]
model_path: 'pretrained/aslfeat/model.ckpt-380000' # 'pretrained/aslfeat/model.ckpt-60000'  # 
overwrite: true
net:
  max_dim: 2048 #1600 #
  config:
    kpt_n: 20000 # 20000
    kpt_refinement: true
    deform_desc: 1
    score_thld: 0.5
    edge_thld: 10
    multi_scale: true
    multi_level: true
    nms_size: 3
    eof_mask: 5
    need_norm: true
    use_peakiness: true
post_format:
  suffix: '_aslfeat20K2048_380'

```
